### ISSUE TITLE
it was not Bypassing the cloudflare in the url

### ISSUE THREAD

**Issue by yazhamuthan-aruchamy** [jongan69/Redbubble_Uploader#8]
the Issue here is in this code:

time.sleep(10)
CFelement = WebDriverWait(drvr, 20).until(EC.visibility_of_element_located((By.CSS_SELECTOR, "label.ctp-checkbox-label")))
CFelement.click()
time.sleep(10)

Issue is 

Traceback (most recent call last):
  File "D:\Python files\Redbubble_Uploader-main\app.py", line 49, in <module>
    CFelement = WebDriverWait(drvr, 20).until(EC.visibility_of_element_located((By.CLASS_NAME, "ctp-checkbox-label")))
  File "C:\Users\yazha\PycharmProjects\pythonProject1\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

![Untitled](https://user-images.githubusercontent.com/129824895/231344219-59cf53e1-c769-4358-a890-3650ad1920d5.png)

it was waiting but not taking the  agruments,
((By.CLASS_NAME, "ctp-checkbox-label"))) i think this was not working properly.

**Comment by jongan69** [comment]
Yes they are trying to block the bots ability to proceed, any updates on findings to work around would be great
